# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1c7b9a1aa48120131adaffab96fd120"
name = "Custom Checkout App"
application_url = "https://jm-between-sentence-rouge.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "onur-test-checkout-extens.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_shipping,write_payment_customizations,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://jm-between-sentence-rouge.trycloudflare.com/auth/callback",
  "https://jm-between-sentence-rouge.trycloudflare.com/auth/shopify/callback",
  "https://jm-between-sentence-rouge.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
