# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c76e8282d4c1b257617de0fd1dfcc9bc"
name = "payment-customization"
application_url = "https://nirvana-match-develop-layers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "onur-test-checkout-extens.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_shipping,write_payment_customizations,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://nirvana-match-develop-layers.trycloudflare.com/auth/callback",
  "https://nirvana-match-develop-layers.trycloudflare.com/auth/shopify/callback",
  "https://nirvana-match-develop-layers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
